export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  originalPrice?: number;
  images: string[];
  description: string;
  shortDescription: string;
  specs: Record<string, string>;
  colors: { name: string; hex: string }[];
  variants: { label: string; value: string }[];
  rating: number;
  reviewCount: number;
  inStock: boolean;
  isNew: boolean;
  isFeatured: boolean;
  isDeal: boolean;
  dealEndsAt?: string;
};

export type Review = {
  id: string;
  productId: string;
  rating: number;
  title: string;
  body: string;
  author: string;
  date: string;
  verified: boolean;
};

export type CartItem = {
  product: Product;
  quantity: number;
  selectedColor: string;
  selectedVariant: string;
};

const dealDate = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();

export const products: Product[] = [
  {
    id: '1',
    slug: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'phones',
    subcategory: 'iphones',
    price: 1650000,
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The most advanced iPhone ever. Featuring the A18 Pro chip, a 48MP Fusion camera system with 5x optical zoom, and a stunning 6.9-inch Super Retina XDR display with ProMotion. Built with aerospace-grade titanium for a premium yet lightweight feel.',
    shortDescription: 'Titanium design, A18 Pro chip, 48MP camera system with 5x zoom, 6.9-inch display.',
    specs: {
      Display: '6.9" Super Retina XDR, 2868x1320, 120Hz ProMotion',
      Chip: 'A18 Pro with 6-core GPU',
      Camera: '48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto',
      Battery: 'Up to 33 hours video playback',
      Storage: '256GB / 512GB / 1TB',
      'Water Resistance': 'IP68 (6 meters, 30 minutes)',
      Weight: '227 g',
      OS: 'iOS 18',
    },
    colors: [
      { name: 'Natural Titanium', hex: '#9a9a8e' },
      { name: 'Blue Titanium', hex: '#3d4856' },
      { name: 'White Titanium', hex: '#f2f1eb' },
      { name: 'Black Titanium', hex: '#3c3b37' },
    ],
    variants: [
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
      { label: '1TB', value: '1tb' },
    ],
    rating: 4.8,
    reviewCount: 342,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isDeal: false,
  },
  {
    id: '2',
    slug: 'samsung-galaxy-s25-ultra',
    name: 'Galaxy S25 Ultra',
    brand: 'Samsung',
    category: 'phones',
    subcategory: 'samsung-galaxy',
    price: 1950000,
    originalPrice: 2200000,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1581993192873-ab7e60c5b4cf?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1610945264803-b22f6e0b2de6?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Samsung\'s ultimate smartphone with the Snapdragon 8 Elite chipset, built-in S Pen, and a 200MP camera sensor. The titanium frame and 6.9-inch Dynamic AMOLED 2X display deliver a premium experience.',
    shortDescription: 'Snapdragon 8 Elite, 200MP camera, S Pen included, titanium frame.',
    specs: {
      Display: '6.9" Dynamic AMOLED 2X, 3120x1440, 120Hz',
      Processor: 'Snapdragon 8 Elite for Galaxy',
      Camera: '200MP Main + 50MP Ultra Wide + 50MP 5x + 10MP 3x',
      Battery: '5000 mAh, 45W fast charging',
      Storage: '256GB / 512GB / 1TB',
      'Water Resistance': 'IP68',
      Weight: '218 g',
      OS: 'Android 15, One UI 7',
    },
    colors: [
      { name: 'Titanium Black', hex: '#2b2b2b' },
      { name: 'Titanium Gray', hex: '#848484' },
      { name: 'Titanium Violet', hex: '#a7a2b4' },
      { name: 'Titanium Blue', hex: '#5b6e8a' },
    ],
    variants: [
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
      { label: '1TB', value: '1tb' },
    ],
    rating: 4.7,
    reviewCount: 218,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '3',
    slug: 'ps5-pro',
    name: 'PlayStation 5 Pro',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'consoles',
    price: 750000,
    images: [
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1586182987320-4f376d338043?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The most powerful PlayStation console ever built. With an upgraded GPU delivering 45% faster rendering, advanced ray tracing, and PlayStation Spectral Super Resolution for stunning 4K visuals at up to 120fps.',
    shortDescription: '45% faster GPU, advanced ray tracing, 2TB SSD, 4K at 120fps.',
    specs: {
      GPU: 'Custom RDNA based, 16.7 TFLOPS',
      CPU: 'AMD Zen 2, 8-core 3.5GHz',
      RAM: '16GB GDDR6',
      Storage: '2TB Custom SSD',
      'Disc Drive': 'Optional (sold separately)',
      Output: '4K 120Hz, 8K support',
      'Ray Tracing': 'Advanced RT with PSSR upscaling',
      Connectivity: 'Wi-Fi 7, Bluetooth 5.1',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [
      { label: 'Digital', value: 'digital' },
      { label: 'Disc Bundle', value: 'disc' },
    ],
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isDeal: false,
  },
  {
    id: '4',
    slug: 'airpods-pro-3',
    name: 'AirPods Pro 3',
    brand: 'Apple',
    category: 'audio',
    subcategory: 'earbuds',
    price: 280000,
    originalPrice: 320000,
    images: [
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Rebuilt from the ground up with the H3 chip. Features clinical-grade hearing health capabilities, Active Noise Cancellation with 2x the performance, and Personalized Spatial Audio with head tracking.',
    shortDescription: 'H3 chip, 2x better ANC, hearing health features, USB-C.',
    specs: {
      Chip: 'Apple H3',
      'Active Noise Cancellation': 'Yes, 2x improvement',
      'Battery Life': '6 hours (ANC on), 30 hours with case',
      Connectivity: 'Bluetooth 5.3',
      'Water Resistance': 'IPX4 (earbuds and case)',
      Charging: 'USB-C, MagSafe, Qi wireless',
      Driver: 'Custom high-excursion driver',
      Weight: '5.3g per earbud',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.9,
    reviewCount: 489,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '5',
    slug: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    category: 'wearables',
    subcategory: 'apple-watch',
    price: 900000,
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1614946219870-0dfe8bfc88f5?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The most rugged and capable Apple Watch. Built with a 49mm titanium case, the brightest Apple Watch display ever at 3000 nits, precision dual-frequency GPS, and up to 72 hours of battery life in Low Power Mode.',
    shortDescription: '49mm titanium, 3000 nits display, 72hr battery, precision GPS.',
    specs: {
      Case: '49mm Titanium',
      Display: 'Always-On Retina LTPO2, 3000 nits',
      Chip: 'Apple S9 SiP with U2',
      Battery: 'Up to 36 hours, 72 hours Low Power Mode',
      'Water Resistance': 'WR100, EN13319',
      GPS: 'Precision dual-frequency L1/L5',
      Storage: '64GB',
      Connectivity: 'LTE, Wi-Fi 4, Bluetooth 5.3, NFC',
    },
    colors: [
      { name: 'Natural Titanium', hex: '#a8a8a0' },
      { name: 'Black Titanium', hex: '#3c3b37' },
    ],
    variants: [
      { label: 'GPS', value: 'gps' },
      { label: 'GPS + Cellular', value: 'cellular' },
    ],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '6',
    slug: 'sony-wh-1000xm5',
    name: 'WH-1000XM5',
    brand: 'Sony',
    category: 'audio',
    subcategory: 'headphones',
    price: 350000,
    originalPrice: 420000,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Industry-leading noise cancellation with Auto NC Optimizer. Features 30-hour battery life, crystal-clear hands-free calling with 8 microphones, and Multipoint connection for seamless switching between devices.',
    shortDescription: 'Industry-leading ANC, 30hr battery, 8 microphones, multipoint.',
    specs: {
      Driver: '30mm carbon fiber composite',
      'Noise Cancellation': 'HD Noise Canceling Processor QN1',
      'Battery Life': '30 hours (ANC on), 40 hours (ANC off)',
      Charging: 'USB-C, 3 min charge = 3 hours',
      Bluetooth: '5.2 with LDAC, AAC, SBC',
      Weight: '250g',
      'Fold Design': 'Flat folding',
      Microphones: '8 microphones, Precise Voice Pickup',
    },
    colors: [
      { name: 'Black', hex: '#2b2b2b' },
      { name: 'Silver', hex: '#c4c4c4' },
      { name: 'Midnight Blue', hex: '#1a2744' },
    ],
    variants: [],
    rating: 4.6,
    reviewCount: 372,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '7',
    slug: 'ipad-air-m3',
    name: 'iPad Air M3',
    brand: 'Apple',
    category: 'phones',
    subcategory: 'iphones',
    price: 620000,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Supercharged by the M3 chip with an 11-inch or 13-inch Liquid Retina display. Supports Apple Pencil Pro and Magic Keyboard for a full creative workstation experience.',
    shortDescription: 'M3 chip, Liquid Retina display, Apple Pencil Pro support.',
    specs: {
      Chip: 'Apple M3 (8-core CPU, 10-core GPU)',
      Display: '11" or 13" Liquid Retina, P3, True Tone',
      Storage: '128GB / 256GB / 512GB / 1TB',
      Camera: '12MP Wide + 12MP Ultra Wide front',
      Battery: 'Up to 10 hours',
      Connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
      Biometrics: 'Touch ID',
      Weight: '462g (11-inch)',
    },
    colors: [
      { name: 'Space Gray', hex: '#68696d' },
      { name: 'Starlight', hex: '#f0e8d8' },
      { name: 'Purple', hex: '#c4b4cc' },
      { name: 'Blue', hex: '#6e80a4' },
    ],
    variants: [
      { label: '11-inch', value: '11' },
      { label: '13-inch', value: '13' },
    ],
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '8',
    slug: 'dualsense-edge',
    name: 'DualSense Edge Controller',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'controllers',
    price: 200000,
    images: [
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The ultra-customizable PlayStation controller with remappable back buttons, adjustable triggers, interchangeable stick caps, and onboard profiles for instant switching between setups.',
    shortDescription: 'Remappable back buttons, adjustable triggers, swappable stick modules.',
    specs: {
      'Back Buttons': '2 sets included (half-dome, lever)',
      Triggers: 'Adjustable travel distance',
      'Stick Caps': '3 types (standard, high dome, low dome)',
      'Stick Modules': 'Replaceable',
      Battery: 'Built-in rechargeable, USB-C',
      Audio: '3.5mm headset jack, built-in mic',
      Haptics: 'Adaptive triggers, haptic feedback',
      Connectivity: 'Bluetooth, USB-C wired',
    },
    colors: [{ name: 'White/Black', hex: '#e8e8e8' }],
    variants: [],
    rating: 4.4,
    reviewCount: 98,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '9',
    slug: 'magsafe-charger-duo',
    name: 'MagSafe Duo Charger',
    brand: 'Apple',
    category: 'accessories',
    subcategory: 'chargers',
    price: 130000,
    images: [
      'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1572177812156-02f75c6f0d0e?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Charge your iPhone and Apple Watch simultaneously with perfectly aligned MagSafe technology. Foldable design for travel, up to 15W wireless charging for iPhone.',
    shortDescription: 'Charge iPhone + Apple Watch together, foldable, 15W MagSafe.',
    specs: {
      'iPhone Charging': 'Up to 15W MagSafe',
      'Watch Charging': 'Fast charging capable',
      Design: 'Foldable leather',
      Cable: 'USB-C, 1m',
      Compatibility: 'iPhone 12+, Apple Watch Series 1+',
      Weight: '132g',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.3,
    reviewCount: 74,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '10',
    slug: 'samsung-galaxy-buds3-pro',
    name: 'Galaxy Buds3 Pro',
    brand: 'Samsung',
    category: 'audio',
    subcategory: 'earbuds',
    price: 250000,
    originalPrice: 300000,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Samsung\'s most intelligent earbuds with 2-way speakers, adaptive ANC, and Ultra High Quality Audio. Blade lights on the stems add a distinctive design touch.',
    shortDescription: '2-way speakers, adaptive ANC, blade lights, Galaxy AI features.',
    specs: {
      Driver: '10.5mm dynamic + 6.1mm planar',
      ANC: 'Adaptive Active Noise Cancellation',
      'Battery Life': '7 hours (ANC on), 30 hours with case',
      Bluetooth: '5.4 with LE Audio',
      Codecs: 'Samsung Seamless, AAC, SBC',
      'Water Resistance': 'IP57',
      Weight: '5.4g per earbud',
      Features: 'Galaxy AI interpreter, Blade Lights',
    },
    colors: [
      { name: 'Silver', hex: '#c4c4c4' },
      { name: 'White', hex: '#f5f5f5' },
    ],
    variants: [],
    rating: 4.5,
    reviewCount: 143,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '11',
    slug: 'apple-watch-se-3',
    name: 'Apple Watch SE 3',
    brand: 'Apple',
    category: 'wearables',
    subcategory: 'apple-watch',
    price: 250000,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'All the essentials of Apple Watch at an accessible price. Health and fitness tracking, crash detection, Emergency SOS, and seamless iPhone integration.',
    shortDescription: 'Essential health tracking, crash detection, S9 chip, affordable.',
    specs: {
      Case: '40mm or 44mm Aluminum',
      Display: 'Retina LTPO OLED',
      Chip: 'Apple S9 SiP',
      Battery: 'Up to 18 hours',
      'Water Resistance': 'WR50',
      Sensors: 'Heart rate, accelerometer, gyroscope',
      Connectivity: 'Wi-Fi, Bluetooth 5.3',
      Features: 'Crash Detection, Emergency SOS, Fall Detection',
    },
    colors: [
      { name: 'Midnight', hex: '#1d1d1f' },
      { name: 'Starlight', hex: '#f0e8d8' },
      { name: 'Silver', hex: '#e3e4e0' },
    ],
    variants: [
      { label: '40mm', value: '40mm' },
      { label: '44mm', value: '44mm' },
    ],
    rating: 4.5,
    reviewCount: 231,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '12',
    slug: 'usb-c-multiport-hub',
    name: 'USB-C 7-in-1 Hub',
    brand: 'Anker',
    category: 'accessories',
    subcategory: 'hubs-adapters',
    price: 65000,
    originalPrice: 80000,
    images: [
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1607706189992-eae578626c86?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Expand your laptop\'s connectivity with HDMI 4K@60Hz, 100W Power Delivery pass-through, USB-A 3.0, USB-C data, SD and microSD card readers. Slim aluminum design.',
    shortDescription: '7 ports: HDMI 4K, 100W PD, USB-A, SD/microSD. Aluminum body.',
    specs: {
      Ports: 'HDMI, USB-C PD, USB-C data, 2x USB-A 3.0, SD, microSD',
      'HDMI Output': '4K@60Hz',
      'Power Delivery': 'Up to 100W pass-through',
      'Data Transfer': 'Up to 5Gbps',
      Material: 'Anodized aluminum',
      Cable: 'Integrated 18cm USB-C',
      Weight: '63g',
    },
    colors: [
      { name: 'Space Gray', hex: '#68696d' },
      { name: 'Silver', hex: '#e3e4e0' },
    ],
    variants: [],
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '13',
    slug: 'jbl-charge-5',
    name: 'Charge 5',
    brand: 'JBL',
    category: 'audio',
    subcategory: 'speakers',
    price: 180000,
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Portable Bluetooth speaker with bold JBL Original Pro Sound, an optimized long-excursion driver, and dual bass radiators. IP67 waterproof and dustproof with 20 hours of playtime.',
    shortDescription: 'JBL Pro Sound, IP67, 20hr battery, built-in powerbank.',
    specs: {
      Driver: '52mm x 70mm racetrack woofer + dual passive radiators',
      Output: '30W RMS',
      Battery: '20 hours, 7500mAh power bank',
      'Water Resistance': 'IP67',
      Bluetooth: '5.1',
      Charging: 'USB-C',
      Weight: '960g',
      Features: 'PartyBoost, Powerbank function',
    },
    colors: [
      { name: 'Black', hex: '#2b2b2b' },
      { name: 'Blue', hex: '#2d5da1' },
      { name: 'Red', hex: '#b8383b' },
      { name: 'Teal', hex: '#4a9a8a' },
    ],
    variants: [],
    rating: 4.7,
    reviewCount: 284,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '14',
    slug: 'iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    category: 'phones',
    subcategory: 'iphones',
    price: 800000,
    originalPrice: 950000,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Dynamic Island, 48MP camera, A16 Bionic chip, and USB-C. The perfect balance of power and value in a color-infused aluminum and glass design.',
    shortDescription: 'A16 Bionic, 48MP camera, Dynamic Island, USB-C.',
    specs: {
      Display: '6.1" Super Retina XDR, 2556x1179',
      Chip: 'A16 Bionic',
      Camera: '48MP Main + 12MP Ultra Wide',
      Battery: 'Up to 20 hours video playback',
      Storage: '128GB / 256GB / 512GB',
      'Water Resistance': 'IP68',
      Weight: '171 g',
      OS: 'iOS 18',
    },
    colors: [
      { name: 'Blue', hex: '#6e80a4' },
      { name: 'Pink', hex: '#f4d2ce' },
      { name: 'Yellow', hex: '#f4e89a' },
      { name: 'Green', hex: '#c4d9c4' },
      { name: 'Black', hex: '#3c3c3c' },
    ],
    variants: [
      { label: '128GB', value: '128gb' },
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
    ],
    rating: 4.6,
    reviewCount: 512,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '15',
    slug: 'ps5-dualsense-controller',
    name: 'DualSense Wireless Controller',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'controllers',
    price: 70000,
    images: [
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1617096200347-cb04ae810b1d?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Experience haptic feedback, adaptive triggers, and a built-in microphone. The iconic two-tone design with a comfortable ergonomic shape for marathon gaming sessions.',
    shortDescription: 'Haptic feedback, adaptive triggers, built-in mic, ergonomic.',
    specs: {
      Haptics: 'Dual actuators, adaptive triggers',
      Audio: 'Built-in microphone, 3.5mm jack',
      Battery: 'Built-in rechargeable, ~12 hours',
      Connectivity: 'Bluetooth 5.1, USB-C',
      Motion: '6-axis motion sensing (gyroscope + accelerometer)',
      Weight: '280g',
      Features: 'Create button, touchpad, speaker',
    },
    colors: [
      { name: 'White', hex: '#e8e8e8' },
      { name: 'Midnight Black', hex: '#1a1a1a' },
      { name: 'Cosmic Red', hex: '#c32038' },
      { name: 'Starlight Blue', hex: '#7ba4cc' },
    ],
    variants: [],
    rating: 4.7,
    reviewCount: 438,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '16',
    slug: 'samsung-galaxy-s25',
    name: 'Galaxy S25',
    brand: 'Samsung',
    category: 'phones',
    subcategory: 'samsung-galaxy',
    price: 800000,
    images: [
      'https://images.unsplash.com/photo-1610945264803-b22f6e0b2de6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Compact flagship with the Snapdragon 8 Elite, a vibrant 6.2-inch FHD+ AMOLED display, and Galaxy AI features built in. The perfect size for one-handed use.',
    shortDescription: 'Snapdragon 8 Elite, 6.2-inch AMOLED, Galaxy AI, compact flagship.',
    specs: {
      Display: '6.2" FHD+ Dynamic AMOLED 2X, 120Hz',
      Processor: 'Snapdragon 8 Elite for Galaxy',
      Camera: '50MP Main + 12MP Ultra Wide + 10MP 3x Telephoto',
      Battery: '4000 mAh, 25W fast charging',
      Storage: '128GB / 256GB',
      'Water Resistance': 'IP68',
      Weight: '162 g',
      OS: 'Android 15, One UI 7',
    },
    colors: [
      { name: 'Navy', hex: '#1a2744' },
      { name: 'Mint', hex: '#a8d5c4' },
      { name: 'Icy Blue', hex: '#c4d8e8' },
      { name: 'Silver Shadow', hex: '#d4d4d4' },
    ],
    variants: [
      { label: '128GB', value: '128gb' },
      { label: '256GB', value: '256gb' },
    ],
    rating: 4.5,
    reviewCount: 176,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '17',
    slug: 'magsafe-leather-case',
    name: 'MagSafe Leather Case',
    brand: 'Apple',
    category: 'accessories',
    subcategory: 'phone-cases',
    price: 60000,
    images: [
      'https://images.unsplash.com/photo-1601972599720-36938d4ecd31?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Premium European leather case with built-in MagSafe magnets for perfect alignment with chargers and accessories. Develops a natural patina over time.',
    shortDescription: 'European leather, MagSafe built-in, develops natural patina.',
    specs: {
      Material: 'European tanned leather',
      MagSafe: 'Built-in magnets',
      Compatibility: 'iPhone 16 series',
      Protection: 'Raised edges for camera and display',
    },
    colors: [
      { name: 'Ink', hex: '#1a2744' },
      { name: 'Taupe', hex: '#a89a8c' },
      { name: 'Umber', hex: '#6b4c3b' },
    ],
    variants: [
      { label: 'iPhone 16', value: 'iphone-16' },
      { label: 'iPhone 16 Pro', value: 'iphone-16-pro' },
      { label: 'iPhone 16 Pro Max', value: 'iphone-16-pro-max' },
    ],
    rating: 4.2,
    reviewCount: 64,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '18',
    slug: 'sony-pulse-elite',
    name: 'Pulse Elite Wireless Headset',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'gaming-headsets',
    price: 150000,
    images: [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Designed for PlayStation with planar magnetic drivers for ultra-low distortion audio. Features lossless wireless with the included USB adapter, retractable boom mic, and AI-enhanced noise rejection.',
    shortDescription: 'Planar magnetic drivers, lossless wireless, retractable mic.',
    specs: {
      Driver: '40mm planar magnetic',
      Audio: 'Lossless 2.4GHz wireless + Bluetooth',
      Microphone: 'Retractable boom, AI noise rejection',
      Battery: 'Up to 30 hours',
      Charging: 'USB-C, charging hanger included',
      Weight: '300g',
      Compatibility: 'PS5, PC, mobile',
      Features: 'PlayStation Link, Tempest 3D AudioTech',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.3,
    reviewCount: 112,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },

  // ── PHONES ──────────────────────────────────────────────────────────────
  {
    id: '19',
    slug: 'google-pixel-9-pro',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    category: 'phones',
    subcategory: 'android',
    price: 1000000,
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Google\'s most advanced phone with the Tensor G4 chip, a triple-camera system co-engineered with Zeiss, and seven years of OS updates. Features the sharpest display Google has ever made.',
    shortDescription: 'Tensor G4, Zeiss triple camera, 7 years updates, 6.3-inch display.',
    specs: {
      Display: '6.3" LTPO OLED, 2992x1344, 1-120Hz',
      Chip: 'Google Tensor G4',
      Camera: '50MP Main + 48MP Ultra Wide + 48MP 5x Telephoto',
      Battery: '4700 mAh, 27W wired, 21W wireless',
      Storage: '128GB / 256GB / 1TB',
      'Water Resistance': 'IP68',
      Weight: '221g',
      OS: 'Android 15',
    },
    colors: [
      { name: 'Obsidian', hex: '#3c3c3c' },
      { name: 'Porcelain', hex: '#f0ece4' },
      { name: 'Hazel', hex: '#8c8c74' },
      { name: 'Rose Quartz', hex: '#e8c4c4' },
    ],
    variants: [
      { label: '128GB', value: '128gb' },
      { label: '256GB', value: '256gb' },
      { label: '1TB', value: '1tb' },
    ],
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '20',
    slug: 'samsung-galaxy-a55',
    name: 'Galaxy A55 5G',
    brand: 'Samsung',
    category: 'phones',
    subcategory: 'samsung-galaxy',
    price: 450000,
    originalPrice: 550000,
    images: [
      'https://images.unsplash.com/photo-1610945264803-b22f6e0b2de6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1581993192873-ab7e60c5b4cf?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Premium mid-range with an Exynos 1480 chip, 50MP OIS camera, IP67 water resistance, and a stunning Super AMOLED display. Get flagship features without the flagship price.',
    shortDescription: 'Exynos 1480, 50MP OIS, IP67, Super AMOLED, 5000mAh.',
    specs: {
      Display: '6.6" FHD+ Super AMOLED, 120Hz',
      Processor: 'Exynos 1480',
      Camera: '50MP OIS Main + 12MP Ultra Wide + 5MP Macro',
      Battery: '5000 mAh, 25W fast charge',
      Storage: '128GB / 256GB',
      'Water Resistance': 'IP67',
      Weight: '213g',
      OS: 'Android 14, One UI 6.1',
    },
    colors: [
      { name: 'Awesome Iceblue', hex: '#b8d4e4' },
      { name: 'Awesome Navy', hex: '#2c3f6b' },
      { name: 'Awesome Lilac', hex: '#c4b4cc' },
    ],
    variants: [
      { label: '128GB', value: '128gb' },
      { label: '256GB', value: '256gb' },
    ],
    rating: 4.5,
    reviewCount: 134,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '21',
    slug: 'oneplus-13',
    name: 'OnePlus 13',
    brand: 'OnePlus',
    category: 'phones',
    subcategory: 'android',
    price: 900000,
    images: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Powered by Snapdragon 8 Elite with a Hasselblad-tuned triple camera system and 100W SUPERVOOC charging that fills to 100% in just 36 minutes. Flagship power, raw and fast.',
    shortDescription: 'Snapdragon 8 Elite, Hasselblad cameras, 100W charging, 6.82-inch.',
    specs: {
      Display: '6.82" LTPO AMOLED, 3168x1440, 1-120Hz',
      Processor: 'Snapdragon 8 Elite',
      Camera: '50MP Main + 50MP Ultra Wide + 50MP 3x Telephoto (Hasselblad)',
      Battery: '6000 mAh, 100W SUPERVOOC wired, 50W wireless',
      Storage: '256GB / 512GB',
      'Water Resistance': 'IP69',
      Weight: '210g',
      OS: 'OxygenOS 15, Android 15',
    },
    colors: [
      { name: 'Black Eclipse', hex: '#1a1a1a' },
      { name: 'Arctic Dawn', hex: '#e8f0f8' },
    ],
    variants: [
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
    ],
    rating: 4.6,
    reviewCount: 97,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },

  // ── GAMING ───────────────────────────────────────────────────────────────
  {
    id: '22',
    slug: 'xbox-series-x',
    name: 'Xbox Series X',
    brand: 'Microsoft',
    category: 'gaming',
    subcategory: 'consoles',
    price: 500000,
    images: [
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The world\'s most powerful console with 12 teraflops of GPU performance, a custom NVMe SSD, and support for 4K at 120fps. Play thousands of games across four generations with backward compatibility.',
    shortDescription: '12 TFLOPS GPU, 4K 120fps, 1TB NVMe SSD, backward compatible.',
    specs: {
      GPU: 'Custom RDNA 2, 12 TFLOPS',
      CPU: 'Custom Zen 2, 8-core 3.8GHz',
      RAM: '16GB GDDR6',
      Storage: '1TB Custom NVMe SSD',
      Output: '4K 120Hz, 8K support',
      'Disc Drive': 'UHD Blu-ray',
      Connectivity: 'Wi-Fi 5, Bluetooth 5.0, Ethernet',
      Audio: 'Dolby Atmos, DTS:X',
    },
    colors: [{ name: 'Carbon Black', hex: '#1a1a1a' }],
    variants: [
      { label: 'Console Only', value: 'console' },
      { label: 'Console + Controller', value: 'bundle' },
    ],
    rating: 4.7,
    reviewCount: 312,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '23',
    slug: 'nintendo-switch-2',
    name: 'Nintendo Switch 2',
    brand: 'Nintendo',
    category: 'gaming',
    subcategory: 'consoles',
    price: 450000,
    images: [
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1586182987320-4f376d338043?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Nintendo\'s next-generation hybrid console with a larger 7.9-inch LCD display, magnetic Joy-Con 2 controllers with a new mouse function, and support for 4K output in TV mode.',
    shortDescription: '7.9-inch display, 4K TV mode, magnetic Joy-Con 2, GameChat.',
    specs: {
      Display: '7.9" LCD, 1080p handheld',
      'TV Output': '4K UHD via dock',
      Storage: '256GB internal + microSD',
      Battery: '2-6.5 hours depending on game',
      Controllers: 'Joy-Con 2 (magnetic, mouse function)',
      Connectivity: 'Wi-Fi 6, Bluetooth 5.3',
      Features: 'GameChat, backward compatible with Switch games',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [{ label: 'Standard', value: 'standard' }],
    rating: 4.8,
    reviewCount: 204,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isDeal: false,
  },
  {
    id: '24',
    slug: 'razer-kishi-v2-pro',
    name: 'Kishi V2 Pro Controller',
    brand: 'Razer',
    category: 'gaming',
    subcategory: 'controllers',
    price: 150000,
    images: [
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Transform your smartphone into a pro gaming handheld. Features Razer\'s mechanical microswitch buttons, haptic feedback, a built-in 3.5mm audio jack, and a universal fit for all Android phones.',
    shortDescription: 'Mechanical microswitches, haptics, 3.5mm jack, fits all Android phones.',
    specs: {
      Buttons: 'Razer mechanical microswitches',
      Triggers: 'Analog with 6-axis IMU',
      Haptics: 'Built-in haptic feedback',
      Audio: '3.5mm headset jack',
      Connectivity: 'USB-C passthrough',
      Compatibility: 'Android 8.0+, universal fit',
      Weight: '117g',
    },
    colors: [{ name: 'Black', hex: '#1a1a1a' }],
    variants: [],
    rating: 4.3,
    reviewCount: 76,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },

  // ── AUDIO ────────────────────────────────────────────────────────────────
  {
    id: '25',
    slug: 'bose-quietcomfort-45',
    name: 'QuietComfort 45',
    brand: 'Bose',
    category: 'audio',
    subcategory: 'headphones',
    price: 280000,
    originalPrice: 330000,
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Legendary Bose noise cancellation meets all-day comfort. Switch between full QuietComfort mode and Aware mode to stay in tune with your surroundings, with 24-hour battery life.',
    shortDescription: 'Bose ANC, Aware mode, 24hr battery, lightweight, USB-C.',
    specs: {
      'Noise Cancellation': 'Bose QuietComfort (world-class ANC)',
      'Battery Life': '24 hours',
      Charging: 'USB-C, 15 min = 3 hours',
      Bluetooth: '5.1 with multipoint',
      Microphones: '2 mics for calls',
      Weight: '240g',
      Foldable: 'Yes',
      Ear Cushions: 'Protein leather over-ear',
    },
    colors: [
      { name: 'White Smoke', hex: '#f0efed' },
      { name: 'Triple Black', hex: '#1a1a1a' },
    ],
    variants: [],
    rating: 4.6,
    reviewCount: 527,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '26',
    slug: 'beats-studio-pro',
    name: 'Beats Studio Pro',
    brand: 'Beats',
    category: 'audio',
    subcategory: 'headphones',
    price: 350000,
    images: [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Professional-grade sound with Personalized Spatial Audio, ANC, and Transparency mode. Compatible with both Apple and Android with lossless USB-C audio and up to 40 hours of battery.',
    shortDescription: 'Lossless USB-C audio, Spatial Audio, ANC, 40hr battery.',
    specs: {
      Driver: '40mm with optimized diaphragm',
      'Noise Cancellation': 'Personalized ANC',
      'Battery Life': '40 hours',
      Charging: 'USB-C (lossless audio), 3.5mm',
      Bluetooth: '5.3',
      'Spatial Audio': 'Personalized with head tracking',
      Compatibility: 'iOS & Android',
      Weight: '260g',
    },
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Deep Brown', hex: '#5c4033' },
      { name: 'Navy', hex: '#1a2744' },
      { name: 'Sandstone', hex: '#c4a882' },
    ],
    variants: [],
    rating: 4.5,
    reviewCount: 198,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '27',
    slug: 'sony-wf-1000xm5',
    name: 'WF-1000XM5',
    brand: 'Sony',
    category: 'audio',
    subcategory: 'earbuds',
    price: 280000,
    originalPrice: 320000,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Sony\'s best-ever wireless earbuds with the new QN2e chip delivering the world\'s best ANC in earbuds. Features 8.4mm drivers, LDAC for high-res audio, and 36 hours total battery.',
    shortDescription: "World's best ANC, LDAC hi-res audio, 8.4mm drivers, 36hr total.",
    specs: {
      Driver: '8.4mm dynamic driver',
      Chip: 'QN2e noise-cancelling + V2 audio',
      ANC: 'Industry-leading in-ear ANC',
      'Battery Life': '8 hours + 28 hours case (LDAC)',
      Charging: 'USB-C, wireless Qi',
      Codecs: 'LDAC, AAC, SBC',
      'Water Resistance': 'IPX4',
      Weight: '5.9g per earbud',
    },
    colors: [
      { name: 'Black', hex: '#2b2b2b' },
      { name: 'Silver', hex: '#c4c4c4' },
    ],
    variants: [],
    rating: 4.8,
    reviewCount: 341,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },

  // ── WEARABLES ─────────────────────────────────────────────────────────────
  {
    id: '28',
    slug: 'samsung-galaxy-watch-7',
    name: 'Galaxy Watch 7',
    brand: 'Samsung',
    category: 'wearables',
    subcategory: 'fitness-trackers',
    price: 300000,
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Powered by a 3nm chip for faster performance and AI-driven health insights. Advanced sleep coaching, irregular heart rhythm detection, and a bright 2000-nit AMOLED display.',
    shortDescription: '3nm chip, AI health, sleep coaching, 40mm or 44mm, Wear OS 5.',
    specs: {
      Display: '40mm: 1.47" / 44mm: 1.5" AMOLED, 2000 nits',
      Chip: 'Exynos W1000 (3nm)',
      Battery: '40mm: 300mAh / 44mm: 425mAh',
      'Water Resistance': '5ATM + IP68, MIL-SPEC',
      OS: 'Wear OS 5 with One UI Watch 6',
      Sensors: 'BioActive (ECG, HRM, SpO2), Skin temp',
      GPS: 'L1 + L5 dual-band',
      Connectivity: 'LTE, Wi-Fi 6, Bluetooth 5.3, NFC',
    },
    colors: [
      { name: 'Green', hex: '#4a7c5a' },
      { name: 'Cream', hex: '#f0e8d8' },
      { name: 'Silver', hex: '#e3e4e0' },
    ],
    variants: [
      { label: '40mm', value: '40mm' },
      { label: '44mm', value: '44mm' },
    ],
    rating: 4.5,
    reviewCount: 167,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '29',
    slug: 'garmin-forerunner-265',
    name: 'Forerunner 265',
    brand: 'Garmin',
    category: 'wearables',
    subcategory: 'fitness-trackers',
    price: 450000,
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'A runner\'s best companion with a bright AMOLED display, Training Readiness score, daily workout suggestions powered by your fitness data, and 13 days of battery life.',
    shortDescription: 'AMOLED display, Training Readiness, daily suggestions, 13-day battery.',
    specs: {
      Display: '1.3" AMOLED, 416x416',
      Battery: '13 days smartwatch, 20 hours GPS',
      GPS: 'Multi-band GNSS',
      'Water Rating': '5ATM',
      Sensors: 'Wrist HRM, SpO2, Barometric altimeter',
      Features: 'Training Readiness, HRV Status, Race Predictor',
      Weight: '47g',
      Connectivity: 'Bluetooth, ANT+, Wi-Fi',
    },
    colors: [
      { name: 'Black/Slate', hex: '#3c3c3c' },
      { name: 'White/Blue', hex: '#e8f0f8' },
      { name: 'Black/Aqua', hex: '#1a1a1a' },
    ],
    variants: [],
    rating: 4.7,
    reviewCount: 223,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '30',
    slug: 'fitbit-charge-6',
    name: 'Charge 6',
    brand: 'Fitbit',
    category: 'wearables',
    subcategory: 'fitness-trackers',
    price: 160000,
    originalPrice: 200000,
    images: [
      'https://images.unsplash.com/photo-1614946219870-0dfe8bfc88f5?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Built-in Google Maps, Google Wallet, and YouTube Music controls bring smart features to your wrist. Clinical-grade heart rate monitoring and an ECG app on your wrist at an accessible price.',
    shortDescription: 'Google Maps/Wallet, ECG app, 7-day battery, built-in GPS.',
    specs: {
      Display: '1.04" AMOLED',
      Battery: 'Up to 7 days',
      GPS: 'Built-in',
      Sensors: 'ECG, cEDA, HRM, SpO2, Skin temp',
      'Water Resistance': '50m',
      Features: 'Google Maps, Wallet, YouTube Music',
      Connectivity: 'Bluetooth, NFC',
      Weight: '22g (no band)',
    },
    colors: [
      { name: 'Obsidian', hex: '#1a1a1a' },
      { name: 'Porcelain', hex: '#f0ece4' },
      { name: 'Coral', hex: '#e87060' },
    ],
    variants: [],
    rating: 4.3,
    reviewCount: 312,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '31',
    slug: 'apple-watch-series-10',
    name: 'Apple Watch Series 10',
    brand: 'Apple',
    category: 'wearables',
    subcategory: 'apple-watch',
    price: 400000,
    images: [
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The thinnest Apple Watch ever. Largest display yet in a refined aluminum or titanium case. Features sleep apnea detection, the S10 chip, and fast 18-hour battery with rapid charging.',
    shortDescription: 'Thinnest ever, sleep apnea detection, S10 chip, 46mm or 42mm.',
    specs: {
      Case: '42mm or 46mm Aluminum / Titanium',
      Display: 'LTPO OLED, widest Apple Watch yet',
      Chip: 'Apple S10 SiP',
      Battery: '18 hours, 80% in 30 min fast charge',
      'Water Resistance': '50m, shallow water diving',
      Features: 'Sleep Apnea Detection, ECG, Crash Detection',
      Connectivity: 'LTE, Wi-Fi 6, Bluetooth 5.3, NFC',
      Weight: '36g (42mm aluminum)',
    },
    colors: [
      { name: 'Jet Black Aluminum', hex: '#1d1d1f' },
      { name: 'Rose Gold Aluminum', hex: '#e8c4b8' },
      { name: 'Silver Aluminum', hex: '#e3e4e0' },
      { name: 'Natural Titanium', hex: '#a8a8a0' },
    ],
    variants: [
      { label: '42mm', value: '42mm' },
      { label: '46mm', value: '46mm' },
    ],
    rating: 4.8,
    reviewCount: 278,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },

  // ── ACCESSORIES ───────────────────────────────────────────────────────────
  {
    id: '32',
    slug: 'anker-65w-nano-charger',
    name: 'Anker 65W Nano Charger',
    brand: 'Anker',
    category: 'accessories',
    subcategory: 'chargers',
    price: 35000,
    images: [
      'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1572177812156-02f75c6f0d0e?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Palm-sized 65W GaN charger that can simultaneously charge a MacBook, iPhone, and AirPods from a single plug. 40% smaller than standard laptop chargers.',
    shortDescription: '65W GaN, 3 ports, charges laptop + phone + earbuds, compact.',
    specs: {
      Output: '65W (single USB-C), 45W+20W (dual)',
      Ports: '2x USB-C + 1x USB-A',
      Technology: 'GaN II, PowerIQ 4.0',
      Size: '40% smaller than standard 65W chargers',
      Safety: 'MultiProtect surge protection',
      Compatibility: 'MacBook, iPhone, Android, tablets',
      Cable: 'Not included',
    },
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'White', hex: '#f5f5f5' },
    ],
    variants: [],
    rating: 4.7,
    reviewCount: 1243,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '33',
    slug: 'belkin-magsafe-stand',
    name: 'Belkin 3-in-1 MagSafe Stand',
    brand: 'Belkin',
    category: 'accessories',
    subcategory: 'stands-mounts',
    price: 150000,
    images: [
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1607706189992-eae578626c86?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The official Apple-designed 3-in-1 charging stand. Simultaneously charges iPhone with 15W MagSafe, Apple Watch with fast charging, and AirPods — all from one power brick.',
    shortDescription: '15W MagSafe + Apple Watch fast charge + AirPods, all-in-one.',
    specs: {
      'iPhone Charging': 'Up to 15W MagSafe',
      'Watch Charging': 'Apple Watch fast charge',
      'AirPods Charging': 'Qi wireless',
      'Power Brick': '30W included',
      MFi: 'Made for MagSafe certified',
      Material: 'Premium plastic + rubber base',
      Cable: 'Integrated 1.2m USB-C',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.5,
    reviewCount: 389,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '34',
    slug: 'apple-airtag-4pack',
    name: 'AirTag 4-Pack',
    brand: 'Apple',
    category: 'accessories',
    subcategory: 'tracking',
    price: 100000,
    images: [
      'https://images.unsplash.com/photo-1601972599720-36938d4ecd31?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Keep track of your keys, wallet, bag, and more with the power of the Find My network — 1 billion+ Apple devices helping locate your items precisely.',
    shortDescription: 'Find My network, Precision Finding, 1-year battery, IP67.',
    specs: {
      Network: 'Apple Find My (1B+ devices)',
      'Precision Finding': 'Ultra Wideband U1 chip',
      Battery: 'CR2032, ~1 year',
      'Water Resistance': 'IP67 (1m, 30 min)',
      Audio: 'Built-in speaker',
      Connectivity: 'Bluetooth 5.0',
      Size: '31.9mm diameter, 8mm height',
      Pack: '4 AirTags',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.8,
    reviewCount: 2341,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '35',
    slug: 'anker-usb-c-cable-6ft',
    name: 'Anker 240W USB-C Cable (6ft)',
    brand: 'Anker',
    category: 'accessories',
    subcategory: 'cables',
    price: 20000,
    images: [
      'https://images.unsplash.com/photo-1572177812156-02f75c6f0d0e?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The only cable you\'ll ever need. Supports 240W charging for laptops, 40Gbps data transfer, and 8K video output. Braided nylon for durability and tangle resistance.',
    shortDescription: '240W charging, 40Gbps data, 8K video, braided nylon, 6ft.',
    specs: {
      'Max Power': '240W (USB PD 3.1)',
      'Data Transfer': 'Up to 40Gbps (USB 4)',
      'Video Output': '8K@60Hz or 4K@120Hz',
      Length: '6ft (1.8m)',
      Material: 'Braided nylon jacket',
      Connector: 'USB-C to USB-C',
      Bends: '35,000 bend lifespan tested',
    },
    colors: [{ name: 'Black', hex: '#1a1a1a' }],
    variants: [],
    rating: 4.6,
    reviewCount: 876,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '36',
    slug: 'esr-iphone-screen-protector',
    name: 'ESR Tempered Glass iPhone 16 Pro',
    brand: 'ESR',
    category: 'accessories',
    subcategory: 'screen-protectors',
    price: 25000,
    images: [
      'https://images.unsplash.com/photo-1607706189992-eae578626c86?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Military-grade tempered glass screen protector with an EasyAlign installation kit included. Scratch-resistant, fingerprint-resistant, and fully compatible with Face ID and Dynamic Island.',
    shortDescription: 'Military-grade glass, EasyAlign kit, Face ID compatible, 3-pack.',
    specs: {
      Material: '9H hardness tempered glass',
      'Touch Sensitivity': '0.3mm ultra-thin',
      Oleophobic: 'Anti-fingerprint coating',
      Installation: 'EasyAlign frame included',
      Compatibility: 'iPhone 16 Pro',
      Pack: '3 protectors',
      'Case Compatible': 'Yes',
    },
    colors: [{ name: 'Clear', hex: '#transparent' }],
    variants: [
      { label: 'iPhone 16 Pro', value: '16-pro' },
      { label: 'iPhone 16 Pro Max', value: '16-pro-max' },
      { label: 'iPhone 16', value: '16' },
    ],
    rating: 4.4,
    reviewCount: 1892,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    rating: 5,
    title: 'Best phone I have ever owned',
    body: 'The camera system is absolutely incredible. The titanium build feels premium without being heavy. Battery lasts me well into the next day even with heavy use.',
    author: 'Marcus Delgado',
    date: '2025-12-15',
    verified: true,
  },
  {
    id: 'r2',
    productId: '1',
    rating: 4,
    title: 'Great phone, minor gripes',
    body: 'Love the 5x zoom and the display is gorgeous. Wish the USB-C supported Thunderbolt speeds though. The Action button is more useful than I expected.',
    author: 'Priya Chandrasekaran',
    date: '2025-11-28',
    verified: true,
  },
  {
    id: 'r3',
    productId: '3',
    rating: 5,
    title: 'Next-gen gaming is here',
    body: 'The graphical upgrade over the standard PS5 is noticeable in every game. Ray tracing performance is dramatically better. Worth every penny if you care about visual fidelity.',
    author: 'Tomasz Kowalski',
    date: '2026-01-10',
    verified: true,
  },
  {
    id: 'r4',
    productId: '4',
    rating: 5,
    title: 'Noise cancellation is unreal',
    body: 'Flew from LAX to Tokyo and could barely hear the engines. Sound quality for music is noticeably better than the previous generation. The hearing test feature is a neat bonus.',
    author: 'Aisha Okoro',
    date: '2025-10-22',
    verified: true,
  },
  {
    id: 'r5',
    productId: '5',
    rating: 4,
    title: 'Built like a tank',
    body: 'Took this hiking through three national parks. Survived rain, dust, and a drop onto granite. GPS tracking was spot-on for trail mapping. Only wish it was a bit lighter.',
    author: 'Rafael Gutierrez',
    date: '2025-09-14',
    verified: true,
  },
  {
    id: 'r6',
    productId: '2',
    rating: 5,
    title: 'Camera blew my mind',
    body: 'The 200MP sensor captures details I never noticed before. Night mode is outstanding and the S Pen integration for photo editing is surprisingly useful. Best Samsung yet.',
    author: 'Elena Voronova',
    date: '2026-02-03',
    verified: true,
  },
  {
    id: 'r7',
    productId: '6',
    rating: 4,
    title: 'Comfortable for all-day wear',
    body: 'Finally headphones that do not hurt after 4 hours. ANC is excellent on flights and in the office. Multipoint switching between my laptop and phone is seamless.',
    author: 'David Nkemelu',
    date: '2025-08-19',
    verified: false,
  },
  {
    id: 'r8',
    productId: '13',
    rating: 5,
    title: 'Pool party essential',
    body: 'This thing is loud for its size and the bass hits hard. Survived getting knocked into the pool. Battery lasted an entire weekend trip. The powerbank feature saved me once too.',
    author: 'Sophia Matsumoto',
    date: '2025-07-30',
    verified: true,
  },
  {
    id: 'r9',
    productId: '8',
    rating: 4,
    title: 'Premium feel, steep price',
    body: 'The back buttons and adjustable triggers made a real difference in competitive shooters. Build quality is excellent. Price is high but justified for serious gamers.',
    author: 'Kwame Asante',
    date: '2025-11-05',
    verified: true,
  },
  {
    id: 'r10',
    productId: '14',
    rating: 5,
    title: 'Fantastic value for the money',
    body: 'Coming from an iPhone 12, the jump to this is massive. USB-C is finally here, the camera is way better than expected, and Dynamic Island is actually useful.',
    author: 'Linnea Eriksson',
    date: '2025-12-20',
    verified: true,
  },
  {
    id: 'r11',
    productId: '1',
    rating: 5,
    title: 'Photography game changer',
    body: 'As a hobbyist photographer the ProRAW files from this phone rival some of my dedicated camera shots. The 5x telephoto is a game changer for street photography.',
    author: 'Hiroshi Tanaka',
    date: '2026-01-28',
    verified: true,
  },
  {
    id: 'r12',
    productId: '3',
    rating: 4,
    title: 'Solid upgrade but disc drive sold separately',
    body: 'Performance is incredible and load times are non-existent. Bit annoying that the disc drive is an add-on purchase. The library of enhanced games keeps growing though.',
    author: 'Camille Dubois',
    date: '2026-02-14',
    verified: false,
  },
];

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getDealProducts(): Product[] {
  return products.filter((p) => p.isDeal);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getRelatedProducts(product: Product): Product[] {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, 4);
}

export function getAllCategories(): string[] {
  return [...new Set(products.map((p) => p.category))];
}

export function getReviewsByProductId(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}
