export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  originalPrice?: number;
  images: string[];
  description: string;
  shortDescription: string;
  specs: Record<string, string>;
  colors: { name: string; hex: string }[];
  variants: { label: string; value: string }[];
  rating: number;
  reviewCount: number;
  inStock: boolean;
  isNew: boolean;
  isFeatured: boolean;
  isDeal: boolean;
  dealEndsAt?: string;
};

export type Review = {
  id: string;
  productId: string;
  rating: number;
  title: string;
  body: string;
  author: string;
  date: string;
  verified: boolean;
};

export type CartItem = {
  product: Product;
  quantity: number;
  selectedColor: string;
  selectedVariant: string;
};

const dealDate = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();

export const products: Product[] = [
  {
    id: '1',
    slug: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'phones',
    subcategory: 'iphones',
    price: 1199,
    images: [
      'https://picsum.photos/seed/iphone-16-pro-max/800/600',
      'https://picsum.photos/seed/iphone-16-pro-max-2/800/600',
      'https://picsum.photos/seed/iphone-16-pro-max-3/800/600',
      'https://picsum.photos/seed/iphone-16-pro-max-4/800/600',
    ],
    description: 'The most advanced iPhone ever. Featuring the A18 Pro chip, a 48MP Fusion camera system with 5x optical zoom, and a stunning 6.9-inch Super Retina XDR display with ProMotion. Built with aerospace-grade titanium for a premium yet lightweight feel.',
    shortDescription: 'Titanium design, A18 Pro chip, 48MP camera system with 5x zoom, 6.9-inch display.',
    specs: {
      Display: '6.9" Super Retina XDR, 2868x1320, 120Hz ProMotion',
      Chip: 'A18 Pro with 6-core GPU',
      Camera: '48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto',
      Battery: 'Up to 33 hours video playback',
      Storage: '256GB / 512GB / 1TB',
      'Water Resistance': 'IP68 (6 meters, 30 minutes)',
      Weight: '227 g',
      OS: 'iOS 18',
    },
    colors: [
      { name: 'Natural Titanium', hex: '#9a9a8e' },
      { name: 'Blue Titanium', hex: '#3d4856' },
      { name: 'White Titanium', hex: '#f2f1eb' },
      { name: 'Black Titanium', hex: '#3c3b37' },
    ],
    variants: [
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
      { label: '1TB', value: '1tb' },
    ],
    rating: 4.8,
    reviewCount: 342,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isDeal: false,
  },
  {
    id: '2',
    slug: 'samsung-galaxy-s25-ultra',
    name: 'Galaxy S25 Ultra',
    brand: 'Samsung',
    category: 'phones',
    subcategory: 'samsung-galaxy',
    price: 1299,
    originalPrice: 1419,
    images: [
      'https://picsum.photos/seed/galaxy-s25-ultra/800/600',
      'https://picsum.photos/seed/galaxy-s25-ultra-2/800/600',
      'https://picsum.photos/seed/galaxy-s25-ultra-3/800/600',
    ],
    description: 'Samsung\'s ultimate smartphone with the Snapdragon 8 Elite chipset, built-in S Pen, and a 200MP camera sensor. The titanium frame and 6.9-inch Dynamic AMOLED 2X display deliver a premium experience.',
    shortDescription: 'Snapdragon 8 Elite, 200MP camera, S Pen included, titanium frame.',
    specs: {
      Display: '6.9" Dynamic AMOLED 2X, 3120x1440, 120Hz',
      Processor: 'Snapdragon 8 Elite for Galaxy',
      Camera: '200MP Main + 50MP Ultra Wide + 50MP 5x + 10MP 3x',
      Battery: '5000 mAh, 45W fast charging',
      Storage: '256GB / 512GB / 1TB',
      'Water Resistance': 'IP68',
      Weight: '218 g',
      OS: 'Android 15, One UI 7',
    },
    colors: [
      { name: 'Titanium Black', hex: '#2b2b2b' },
      { name: 'Titanium Gray', hex: '#848484' },
      { name: 'Titanium Violet', hex: '#a7a2b4' },
      { name: 'Titanium Blue', hex: '#5b6e8a' },
    ],
    variants: [
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
      { label: '1TB', value: '1tb' },
    ],
    rating: 4.7,
    reviewCount: 218,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '3',
    slug: 'ps5-pro',
    name: 'PlayStation 5 Pro',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'consoles',
    price: 699,
    images: [
      'https://picsum.photos/seed/ps5-pro/800/600',
      'https://picsum.photos/seed/ps5-pro-2/800/600',
      'https://picsum.photos/seed/ps5-pro-3/800/600',
    ],
    description: 'The most powerful PlayStation console ever built. With an upgraded GPU delivering 45% faster rendering, advanced ray tracing, and PlayStation Spectral Super Resolution for stunning 4K visuals at up to 120fps.',
    shortDescription: '45% faster GPU, advanced ray tracing, 2TB SSD, 4K at 120fps.',
    specs: {
      GPU: 'Custom RDNA based, 16.7 TFLOPS',
      CPU: 'AMD Zen 2, 8-core 3.5GHz',
      RAM: '16GB GDDR6',
      Storage: '2TB Custom SSD',
      'Disc Drive': 'Optional (sold separately)',
      Output: '4K 120Hz, 8K support',
      'Ray Tracing': 'Advanced RT with PSSR upscaling',
      Connectivity: 'Wi-Fi 7, Bluetooth 5.1',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [
      { label: 'Digital', value: 'digital' },
      { label: 'Disc Bundle', value: 'disc' },
    ],
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isDeal: false,
  },
  {
    id: '4',
    slug: 'airpods-pro-3',
    name: 'AirPods Pro 3',
    brand: 'Apple',
    category: 'audio',
    subcategory: 'earbuds',
    price: 249,
    originalPrice: 279,
    images: [
      'https://picsum.photos/seed/airpods-pro-3/800/600',
      'https://picsum.photos/seed/airpods-pro-3-2/800/600',
    ],
    description: 'Rebuilt from the ground up with the H3 chip. Features clinical-grade hearing health capabilities, Active Noise Cancellation with 2x the performance, and Personalized Spatial Audio with head tracking.',
    shortDescription: 'H3 chip, 2x better ANC, hearing health features, USB-C.',
    specs: {
      Chip: 'Apple H3',
      'Active Noise Cancellation': 'Yes, 2x improvement',
      'Battery Life': '6 hours (ANC on), 30 hours with case',
      Connectivity: 'Bluetooth 5.3',
      'Water Resistance': 'IPX4 (earbuds and case)',
      Charging: 'USB-C, MagSafe, Qi wireless',
      Driver: 'Custom high-excursion driver',
      Weight: '5.3g per earbud',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.9,
    reviewCount: 489,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '5',
    slug: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    category: 'wearables',
    subcategory: 'apple-watch',
    price: 799,
    images: [
      'https://picsum.photos/seed/apple-watch-ultra-2/800/600',
      'https://picsum.photos/seed/apple-watch-ultra-2-2/800/600',
      'https://picsum.photos/seed/apple-watch-ultra-2-3/800/600',
    ],
    description: 'The most rugged and capable Apple Watch. Built with a 49mm titanium case, the brightest Apple Watch display ever at 3000 nits, precision dual-frequency GPS, and up to 72 hours of battery life in Low Power Mode.',
    shortDescription: '49mm titanium, 3000 nits display, 72hr battery, precision GPS.',
    specs: {
      Case: '49mm Titanium',
      Display: 'Always-On Retina LTPO2, 3000 nits',
      Chip: 'Apple S9 SiP with U2',
      Battery: 'Up to 36 hours, 72 hours Low Power Mode',
      'Water Resistance': 'WR100, EN13319',
      GPS: 'Precision dual-frequency L1/L5',
      Storage: '64GB',
      Connectivity: 'LTE, Wi-Fi 4, Bluetooth 5.3, NFC',
    },
    colors: [
      { name: 'Natural Titanium', hex: '#a8a8a0' },
      { name: 'Black Titanium', hex: '#3c3b37' },
    ],
    variants: [
      { label: 'GPS', value: 'gps' },
      { label: 'GPS + Cellular', value: 'cellular' },
    ],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '6',
    slug: 'sony-wh-1000xm5',
    name: 'WH-1000XM5',
    brand: 'Sony',
    category: 'audio',
    subcategory: 'headphones',
    price: 348,
    originalPrice: 399,
    images: [
      'https://picsum.photos/seed/sony-wh-1000xm5/800/600',
      'https://picsum.photos/seed/sony-wh-1000xm5-2/800/600',
    ],
    description: 'Industry-leading noise cancellation with Auto NC Optimizer. Features 30-hour battery life, crystal-clear hands-free calling with 8 microphones, and Multipoint connection for seamless switching between devices.',
    shortDescription: 'Industry-leading ANC, 30hr battery, 8 microphones, multipoint.',
    specs: {
      Driver: '30mm carbon fiber composite',
      'Noise Cancellation': 'HD Noise Canceling Processor QN1',
      'Battery Life': '30 hours (ANC on), 40 hours (ANC off)',
      Charging: 'USB-C, 3 min charge = 3 hours',
      Bluetooth: '5.2 with LDAC, AAC, SBC',
      Weight: '250g',
      'Fold Design': 'Flat folding',
      Microphones: '8 microphones, Precise Voice Pickup',
    },
    colors: [
      { name: 'Black', hex: '#2b2b2b' },
      { name: 'Silver', hex: '#c4c4c4' },
      { name: 'Midnight Blue', hex: '#1a2744' },
    ],
    variants: [],
    rating: 4.6,
    reviewCount: 372,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '7',
    slug: 'ipad-air-m3',
    name: 'iPad Air M3',
    brand: 'Apple',
    category: 'phones',
    subcategory: 'iphones',
    price: 599,
    images: [
      'https://picsum.photos/seed/ipad-air-m3/800/600',
      'https://picsum.photos/seed/ipad-air-m3-2/800/600',
    ],
    description: 'Supercharged by the M3 chip with an 11-inch or 13-inch Liquid Retina display. Supports Apple Pencil Pro and Magic Keyboard for a full creative workstation experience.',
    shortDescription: 'M3 chip, Liquid Retina display, Apple Pencil Pro support.',
    specs: {
      Chip: 'Apple M3 (8-core CPU, 10-core GPU)',
      Display: '11" or 13" Liquid Retina, P3, True Tone',
      Storage: '128GB / 256GB / 512GB / 1TB',
      Camera: '12MP Wide + 12MP Ultra Wide front',
      Battery: 'Up to 10 hours',
      Connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
      Biometrics: 'Touch ID',
      Weight: '462g (11-inch)',
    },
    colors: [
      { name: 'Space Gray', hex: '#68696d' },
      { name: 'Starlight', hex: '#f0e8d8' },
      { name: 'Purple', hex: '#c4b4cc' },
      { name: 'Blue', hex: '#6e80a4' },
    ],
    variants: [
      { label: '11-inch', value: '11' },
      { label: '13-inch', value: '13' },
    ],
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '8',
    slug: 'dualsense-edge',
    name: 'DualSense Edge Controller',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'controllers',
    price: 199,
    images: [
      'https://picsum.photos/seed/dualsense-edge/800/600',
      'https://picsum.photos/seed/dualsense-edge-2/800/600',
    ],
    description: 'The ultra-customizable PlayStation controller with remappable back buttons, adjustable triggers, interchangeable stick caps, and onboard profiles for instant switching between setups.',
    shortDescription: 'Remappable back buttons, adjustable triggers, swappable stick modules.',
    specs: {
      'Back Buttons': '2 sets included (half-dome, lever)',
      Triggers: 'Adjustable travel distance',
      'Stick Caps': '3 types (standard, high dome, low dome)',
      'Stick Modules': 'Replaceable',
      Battery: 'Built-in rechargeable, USB-C',
      Audio: '3.5mm headset jack, built-in mic',
      Haptics: 'Adaptive triggers, haptic feedback',
      Connectivity: 'Bluetooth, USB-C wired',
    },
    colors: [{ name: 'White/Black', hex: '#e8e8e8' }],
    variants: [],
    rating: 4.4,
    reviewCount: 98,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '9',
    slug: 'magsafe-charger-duo',
    name: 'MagSafe Duo Charger',
    brand: 'Apple',
    category: 'accessories',
    subcategory: 'chargers',
    price: 129,
    images: [
      'https://picsum.photos/seed/magsafe-duo/800/600',
      'https://picsum.photos/seed/magsafe-duo-2/800/600',
    ],
    description: 'Charge your iPhone and Apple Watch simultaneously with perfectly aligned MagSafe technology. Foldable design for travel, up to 15W wireless charging for iPhone.',
    shortDescription: 'Charge iPhone + Apple Watch together, foldable, 15W MagSafe.',
    specs: {
      'iPhone Charging': 'Up to 15W MagSafe',
      'Watch Charging': 'Fast charging capable',
      Design: 'Foldable leather',
      Cable: 'USB-C, 1m',
      Compatibility: 'iPhone 12+, Apple Watch Series 1+',
      Weight: '132g',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.3,
    reviewCount: 74,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '10',
    slug: 'samsung-galaxy-buds3-pro',
    name: 'Galaxy Buds3 Pro',
    brand: 'Samsung',
    category: 'audio',
    subcategory: 'earbuds',
    price: 249,
    originalPrice: 279,
    images: [
      'https://picsum.photos/seed/galaxy-buds3-pro/800/600',
      'https://picsum.photos/seed/galaxy-buds3-pro-2/800/600',
    ],
    description: 'Samsung\'s most intelligent earbuds with 2-way speakers, adaptive ANC, and Ultra High Quality Audio. Blade lights on the stems add a distinctive design touch.',
    shortDescription: '2-way speakers, adaptive ANC, blade lights, Galaxy AI features.',
    specs: {
      Driver: '10.5mm dynamic + 6.1mm planar',
      ANC: 'Adaptive Active Noise Cancellation',
      'Battery Life': '7 hours (ANC on), 30 hours with case',
      Bluetooth: '5.4 with LE Audio',
      Codecs: 'Samsung Seamless, AAC, SBC',
      'Water Resistance': 'IP57',
      Weight: '5.4g per earbud',
      Features: 'Galaxy AI interpreter, Blade Lights',
    },
    colors: [
      { name: 'Silver', hex: '#c4c4c4' },
      { name: 'White', hex: '#f5f5f5' },
    ],
    variants: [],
    rating: 4.5,
    reviewCount: 143,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '11',
    slug: 'apple-watch-se-3',
    name: 'Apple Watch SE 3',
    brand: 'Apple',
    category: 'wearables',
    subcategory: 'apple-watch',
    price: 249,
    images: [
      'https://picsum.photos/seed/apple-watch-se-3/800/600',
      'https://picsum.photos/seed/apple-watch-se-3-2/800/600',
    ],
    description: 'All the essentials of Apple Watch at an accessible price. Health and fitness tracking, crash detection, Emergency SOS, and seamless iPhone integration.',
    shortDescription: 'Essential health tracking, crash detection, S9 chip, affordable.',
    specs: {
      Case: '40mm or 44mm Aluminum',
      Display: 'Retina LTPO OLED',
      Chip: 'Apple S9 SiP',
      Battery: 'Up to 18 hours',
      'Water Resistance': 'WR50',
      Sensors: 'Heart rate, accelerometer, gyroscope',
      Connectivity: 'Wi-Fi, Bluetooth 5.3',
      Features: 'Crash Detection, Emergency SOS, Fall Detection',
    },
    colors: [
      { name: 'Midnight', hex: '#1d1d1f' },
      { name: 'Starlight', hex: '#f0e8d8' },
      { name: 'Silver', hex: '#e3e4e0' },
    ],
    variants: [
      { label: '40mm', value: '40mm' },
      { label: '44mm', value: '44mm' },
    ],
    rating: 4.5,
    reviewCount: 231,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '12',
    slug: 'usb-c-multiport-hub',
    name: 'USB-C 7-in-1 Hub',
    brand: 'Anker',
    category: 'accessories',
    subcategory: 'hubs-adapters',
    price: 65,
    originalPrice: 79,
    images: [
      'https://picsum.photos/seed/usb-c-hub/800/600',
      'https://picsum.photos/seed/usb-c-hub-2/800/600',
    ],
    description: 'Expand your laptop\'s connectivity with HDMI 4K@60Hz, 100W Power Delivery pass-through, USB-A 3.0, USB-C data, SD and microSD card readers. Slim aluminum design.',
    shortDescription: '7 ports: HDMI 4K, 100W PD, USB-A, SD/microSD. Aluminum body.',
    specs: {
      Ports: 'HDMI, USB-C PD, USB-C data, 2x USB-A 3.0, SD, microSD',
      'HDMI Output': '4K@60Hz',
      'Power Delivery': 'Up to 100W pass-through',
      'Data Transfer': 'Up to 5Gbps',
      Material: 'Anodized aluminum',
      Cable: 'Integrated 18cm USB-C',
      Weight: '63g',
    },
    colors: [
      { name: 'Space Gray', hex: '#68696d' },
      { name: 'Silver', hex: '#e3e4e0' },
    ],
    variants: [],
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '13',
    slug: 'jbl-charge-5',
    name: 'Charge 5',
    brand: 'JBL',
    category: 'audio',
    subcategory: 'speakers',
    price: 179,
    images: [
      'https://picsum.photos/seed/jbl-charge-5/800/600',
      'https://picsum.photos/seed/jbl-charge-5-2/800/600',
    ],
    description: 'Portable Bluetooth speaker with bold JBL Original Pro Sound, an optimized long-excursion driver, and dual bass radiators. IP67 waterproof and dustproof with 20 hours of playtime.',
    shortDescription: 'JBL Pro Sound, IP67, 20hr battery, built-in powerbank.',
    specs: {
      Driver: '52mm x 70mm racetrack woofer + dual passive radiators',
      Output: '30W RMS',
      Battery: '20 hours, 7500mAh power bank',
      'Water Resistance': 'IP67',
      Bluetooth: '5.1',
      Charging: 'USB-C',
      Weight: '960g',
      Features: 'PartyBoost, Powerbank function',
    },
    colors: [
      { name: 'Black', hex: '#2b2b2b' },
      { name: 'Blue', hex: '#2d5da1' },
      { name: 'Red', hex: '#b8383b' },
      { name: 'Teal', hex: '#4a9a8a' },
    ],
    variants: [],
    rating: 4.7,
    reviewCount: 284,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '14',
    slug: 'iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    category: 'phones',
    subcategory: 'iphones',
    price: 799,
    originalPrice: 899,
    images: [
      'https://picsum.photos/seed/iphone-15/800/600',
      'https://picsum.photos/seed/iphone-15-2/800/600',
    ],
    description: 'Dynamic Island, 48MP camera, A16 Bionic chip, and USB-C. The perfect balance of power and value in a color-infused aluminum and glass design.',
    shortDescription: 'A16 Bionic, 48MP camera, Dynamic Island, USB-C.',
    specs: {
      Display: '6.1" Super Retina XDR, 2556x1179',
      Chip: 'A16 Bionic',
      Camera: '48MP Main + 12MP Ultra Wide',
      Battery: 'Up to 20 hours video playback',
      Storage: '128GB / 256GB / 512GB',
      'Water Resistance': 'IP68',
      Weight: '171 g',
      OS: 'iOS 18',
    },
    colors: [
      { name: 'Blue', hex: '#6e80a4' },
      { name: 'Pink', hex: '#f4d2ce' },
      { name: 'Yellow', hex: '#f4e89a' },
      { name: 'Green', hex: '#c4d9c4' },
      { name: 'Black', hex: '#3c3c3c' },
    ],
    variants: [
      { label: '128GB', value: '128gb' },
      { label: '256GB', value: '256gb' },
      { label: '512GB', value: '512gb' },
    ],
    rating: 4.6,
    reviewCount: 512,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: true,
    dealEndsAt: dealDate,
  },
  {
    id: '15',
    slug: 'ps5-dualsense-controller',
    name: 'DualSense Wireless Controller',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'controllers',
    price: 69,
    images: [
      'https://picsum.photos/seed/dualsense/800/600',
      'https://picsum.photos/seed/dualsense-2/800/600',
    ],
    description: 'Experience haptic feedback, adaptive triggers, and a built-in microphone. The iconic two-tone design with a comfortable ergonomic shape for marathon gaming sessions.',
    shortDescription: 'Haptic feedback, adaptive triggers, built-in mic, ergonomic.',
    specs: {
      Haptics: 'Dual actuators, adaptive triggers',
      Audio: 'Built-in microphone, 3.5mm jack',
      Battery: 'Built-in rechargeable, ~12 hours',
      Connectivity: 'Bluetooth 5.1, USB-C',
      Motion: '6-axis motion sensing (gyroscope + accelerometer)',
      Weight: '280g',
      Features: 'Create button, touchpad, speaker',
    },
    colors: [
      { name: 'White', hex: '#e8e8e8' },
      { name: 'Midnight Black', hex: '#1a1a1a' },
      { name: 'Cosmic Red', hex: '#c32038' },
      { name: 'Starlight Blue', hex: '#7ba4cc' },
    ],
    variants: [],
    rating: 4.7,
    reviewCount: 438,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '16',
    slug: 'samsung-galaxy-s25',
    name: 'Galaxy S25',
    brand: 'Samsung',
    category: 'phones',
    subcategory: 'samsung-galaxy',
    price: 799,
    images: [
      'https://picsum.photos/seed/galaxy-s25/800/600',
      'https://picsum.photos/seed/galaxy-s25-2/800/600',
    ],
    description: 'Compact flagship with the Snapdragon 8 Elite, a vibrant 6.2-inch FHD+ AMOLED display, and Galaxy AI features built in. The perfect size for one-handed use.',
    shortDescription: 'Snapdragon 8 Elite, 6.2-inch AMOLED, Galaxy AI, compact flagship.',
    specs: {
      Display: '6.2" FHD+ Dynamic AMOLED 2X, 120Hz',
      Processor: 'Snapdragon 8 Elite for Galaxy',
      Camera: '50MP Main + 12MP Ultra Wide + 10MP 3x Telephoto',
      Battery: '4000 mAh, 25W fast charging',
      Storage: '128GB / 256GB',
      'Water Resistance': 'IP68',
      Weight: '162 g',
      OS: 'Android 15, One UI 7',
    },
    colors: [
      { name: 'Navy', hex: '#1a2744' },
      { name: 'Mint', hex: '#a8d5c4' },
      { name: 'Icy Blue', hex: '#c4d8e8' },
      { name: 'Silver Shadow', hex: '#d4d4d4' },
    ],
    variants: [
      { label: '128GB', value: '128gb' },
      { label: '256GB', value: '256gb' },
    ],
    rating: 4.5,
    reviewCount: 176,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '17',
    slug: 'magsafe-leather-case',
    name: 'MagSafe Leather Case',
    brand: 'Apple',
    category: 'accessories',
    subcategory: 'phone-cases',
    price: 59,
    images: [
      'https://picsum.photos/seed/magsafe-case/800/600',
    ],
    description: 'Premium European leather case with built-in MagSafe magnets for perfect alignment with chargers and accessories. Develops a natural patina over time.',
    shortDescription: 'European leather, MagSafe built-in, develops natural patina.',
    specs: {
      Material: 'European tanned leather',
      MagSafe: 'Built-in magnets',
      Compatibility: 'iPhone 16 series',
      Protection: 'Raised edges for camera and display',
    },
    colors: [
      { name: 'Ink', hex: '#1a2744' },
      { name: 'Taupe', hex: '#a89a8c' },
      { name: 'Umber', hex: '#6b4c3b' },
    ],
    variants: [
      { label: 'iPhone 16', value: 'iphone-16' },
      { label: 'iPhone 16 Pro', value: 'iphone-16-pro' },
      { label: 'iPhone 16 Pro Max', value: 'iphone-16-pro-max' },
    ],
    rating: 4.2,
    reviewCount: 64,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
  {
    id: '18',
    slug: 'sony-pulse-elite',
    name: 'Pulse Elite Wireless Headset',
    brand: 'Sony',
    category: 'gaming',
    subcategory: 'gaming-headsets',
    price: 149,
    images: [
      'https://picsum.photos/seed/pulse-elite/800/600',
      'https://picsum.photos/seed/pulse-elite-2/800/600',
    ],
    description: 'Designed for PlayStation with planar magnetic drivers for ultra-low distortion audio. Features lossless wireless with the included USB adapter, retractable boom mic, and AI-enhanced noise rejection.',
    shortDescription: 'Planar magnetic drivers, lossless wireless, retractable mic.',
    specs: {
      Driver: '40mm planar magnetic',
      Audio: 'Lossless 2.4GHz wireless + Bluetooth',
      Microphone: 'Retractable boom, AI noise rejection',
      Battery: 'Up to 30 hours',
      Charging: 'USB-C, charging hanger included',
      Weight: '300g',
      Compatibility: 'PS5, PC, mobile',
      Features: 'PlayStation Link, Tempest 3D AudioTech',
    },
    colors: [{ name: 'White', hex: '#f5f5f5' }],
    variants: [],
    rating: 4.3,
    reviewCount: 112,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isDeal: false,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    rating: 5,
    title: 'Best phone I have ever owned',
    body: 'The camera system is absolutely incredible. The titanium build feels premium without being heavy. Battery lasts me well into the next day even with heavy use.',
    author: 'Marcus Delgado',
    date: '2025-12-15',
    verified: true,
  },
  {
    id: 'r2',
    productId: '1',
    rating: 4,
    title: 'Great phone, minor gripes',
    body: 'Love the 5x zoom and the display is gorgeous. Wish the USB-C supported Thunderbolt speeds though. The Action button is more useful than I expected.',
    author: 'Priya Chandrasekaran',
    date: '2025-11-28',
    verified: true,
  },
  {
    id: 'r3',
    productId: '3',
    rating: 5,
    title: 'Next-gen gaming is here',
    body: 'The graphical upgrade over the standard PS5 is noticeable in every game. Ray tracing performance is dramatically better. Worth every penny if you care about visual fidelity.',
    author: 'Tomasz Kowalski',
    date: '2026-01-10',
    verified: true,
  },
  {
    id: 'r4',
    productId: '4',
    rating: 5,
    title: 'Noise cancellation is unreal',
    body: 'Flew from LAX to Tokyo and could barely hear the engines. Sound quality for music is noticeably better than the previous generation. The hearing test feature is a neat bonus.',
    author: 'Aisha Okoro',
    date: '2025-10-22',
    verified: true,
  },
  {
    id: 'r5',
    productId: '5',
    rating: 4,
    title: 'Built like a tank',
    body: 'Took this hiking through three national parks. Survived rain, dust, and a drop onto granite. GPS tracking was spot-on for trail mapping. Only wish it was a bit lighter.',
    author: 'Rafael Gutierrez',
    date: '2025-09-14',
    verified: true,
  },
  {
    id: 'r6',
    productId: '2',
    rating: 5,
    title: 'Camera blew my mind',
    body: 'The 200MP sensor captures details I never noticed before. Night mode is outstanding and the S Pen integration for photo editing is surprisingly useful. Best Samsung yet.',
    author: 'Elena Voronova',
    date: '2026-02-03',
    verified: true,
  },
  {
    id: 'r7',
    productId: '6',
    rating: 4,
    title: 'Comfortable for all-day wear',
    body: 'Finally headphones that do not hurt after 4 hours. ANC is excellent on flights and in the office. Multipoint switching between my laptop and phone is seamless.',
    author: 'David Nkemelu',
    date: '2025-08-19',
    verified: false,
  },
  {
    id: 'r8',
    productId: '13',
    rating: 5,
    title: 'Pool party essential',
    body: 'This thing is loud for its size and the bass hits hard. Survived getting knocked into the pool. Battery lasted an entire weekend trip. The powerbank feature saved me once too.',
    author: 'Sophia Matsumoto',
    date: '2025-07-30',
    verified: true,
  },
  {
    id: 'r9',
    productId: '8',
    rating: 4,
    title: 'Premium feel, steep price',
    body: 'The back buttons and adjustable triggers made a real difference in competitive shooters. Build quality is excellent. Price is high but justified for serious gamers.',
    author: 'Kwame Asante',
    date: '2025-11-05',
    verified: true,
  },
  {
    id: 'r10',
    productId: '14',
    rating: 5,
    title: 'Fantastic value for the money',
    body: 'Coming from an iPhone 12, the jump to this is massive. USB-C is finally here, the camera is way better than expected, and Dynamic Island is actually useful.',
    author: 'Linnea Eriksson',
    date: '2025-12-20',
    verified: true,
  },
  {
    id: 'r11',
    productId: '1',
    rating: 5,
    title: 'Photography game changer',
    body: 'As a hobbyist photographer the ProRAW files from this phone rival some of my dedicated camera shots. The 5x telephoto is a game changer for street photography.',
    author: 'Hiroshi Tanaka',
    date: '2026-01-28',
    verified: true,
  },
  {
    id: 'r12',
    productId: '3',
    rating: 4,
    title: 'Solid upgrade but disc drive sold separately',
    body: 'Performance is incredible and load times are non-existent. Bit annoying that the disc drive is an add-on purchase. The library of enhanced games keeps growing though.',
    author: 'Camille Dubois',
    date: '2026-02-14',
    verified: false,
  },
];

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getDealProducts(): Product[] {
  return products.filter((p) => p.isDeal);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getRelatedProducts(product: Product): Product[] {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, 4);
}

export function getAllCategories(): string[] {
  return [...new Set(products.map((p) => p.category))];
}

export function getReviewsByProductId(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}
